import { useEffect, useState } from 'react';
import { Link, NavLink, Route, Routes } from 'react-router-dom';
import { AccessibilityPanel, Badge, Button, Card, Mascot, MascotBubble, PageHeader, ProgressBar, SectionHeader } from '../components/ui';
import { GameRunner } from '../games/GameRunner';
import { SpeechAssessmentRunner } from '../games/SpeechAssessmentRunner';
import { ChildAssessmentHub } from './ChildAssessmentHub';
import { PracticeRunner } from '../games/practice/PracticeRunner';
import { LexiWidget } from '../chatbot/LexiWidget';
import { ParentDashboard } from './ParentDashboard';

const nav = [['/', 'Explore'], ['/how-it-works', 'How it works'], ['/research', 'Research']] as const;

function Layout({ children }: { children: React.ReactNode }) {
  const [menuOpen, setMenuOpen] = useState(false);
  const [settingsOpen, setSettingsOpen] = useState(false);
  return <div className="app-shell">
    <nav className={`site-nav ${menuOpen ? 'menu-open' : ''}`}>
      <Link className="brand" to="/" onClick={() => setMenuOpen(false)}><span className="brand-mark">✦</span><span>Dyscover</span></Link>
      <button className="menu-button" onClick={() => setMenuOpen(value => !value)} aria-expanded={menuOpen} aria-label="Toggle navigation"><span /><span /><span /></button>
      <div className="nav-links">{nav.map(([to, label]) => <NavLink key={to} to={to} onClick={() => setMenuOpen(false)} className={({ isActive }) => isActive ? 'active' : ''}>{label}</NavLink>)}<span className="nav-divider" /><NavLink to="/parent/dashboard" onClick={() => setMenuOpen(false)} className="parent-link">For parents</NavLink><Link className="nav-cta" to="/child/home" onClick={() => setMenuOpen(false)}>Start screening <span>↗</span></Link><button className="settings-button" onClick={() => setSettingsOpen(value => !value)} aria-label="Open accessibility settings" aria-expanded={settingsOpen}>Aa</button></div>
      <AccessibilityPanel open={settingsOpen} onClose={() => setSettingsOpen(false)} />
    </nav>
    <main className="main">{children}</main>
    <footer className="footer"><div><Link className="brand footer-brand" to="/"><span className="brand-mark">✦</span>Dyscover</Link><p>A little world built around how children learn.</p></div><div className="footer-links"><Link to="/about">About</Link><Link to="/contact">Contact</Link><Link to="/research">Research</Link></div><small>Dyscover is a non-diagnostic screening and support experience.</small></footer>
    <LexiWidget />
  </div>;
}

function FloatingDecor() { return <><span className="float-shape shape-star">✦</span><span className="float-shape shape-cross">+</span><span className="float-shape shape-dot" /><span className="float-shape shape-letter">a</span></>; }

function Home() { return <>
  <section className="home-hero">
    <FloatingDecor />
    <div className="hero-copy"><span className="eyebrow">A little world for curious minds</span><h1>Discover how <em>you</em> learn.</h1><p className="hero-lede">Every mind has its own way of finding the words. Dyscover makes early learning patterns easier to notice, understand, and support.</p><div className="actions"><Link className="button button-sun" to="/child/home">Start the adventure <span>→</span></Link><Link className="text-link" to="/how-it-works">See how it works <span>↗</span></Link></div><p className="hero-note"><span>✦</span> Gentle activities. Clearer conversations. No labels.</p></div>
    <div className="hero-scene"><div className="scene-sun" /><div className="scene-cloud cloud-one" /><div className="scene-cloud cloud-two" /><div className="scene-hill hill-back" /><div className="scene-hill hill-front" /><div className="scene-path" /><div className="scene-book"><span>abc</span></div><div className="scene-star star-one">✦</div><div className="scene-star star-two">✦</div><Mascot mood="excited" size="large" /></div>
  </section>
  <section className="section intro-section"><div className="section-heading centered"><span className="eyebrow">Learning looks different for everyone</span><h2>Noticing is the first step.</h2><p>Good support starts with curiosity, not assumptions. Dyscover uses short, playful activities to build a fuller picture of how a child interacts with words, symbols, and patterns.</p></div><div className="story-grid"><Card className="story-card story-card-lavender"><span className="story-number">01</span><div className="story-icon icon-loop">↻</div><h3>Play without pressure</h3><p>Small activities feel like an adventure, not a test.</p><Link className="card-link" to="/child/home">Meet the explorer <span>→</span></Link></Card><Card className="story-card story-card-blue"><span className="story-number">02</span><div className="story-icon icon-spark">✦</div><h3>Notice the patterns</h3><p>We keep useful observations connected to each activity.</p><Link className="card-link" to="/research">See our approach <span>→</span></Link></Card><Card className="story-card story-card-mint"><span className="story-number">03</span><div className="story-icon icon-leaf">⌁</div><h3>Grow the conversation</h3><p>Clearer information can lead to more helpful next steps.</p><Link className="card-link" to="/about">Why it matters <span>→</span></Link></Card></div></section>
  <section className="section signals-section"><div className="signals-art"><div className="signal-orbit orbit-one" /><div className="signal-orbit orbit-two" /><div className="signal-core"><span>✦</span></div><span className="signal-chip chip-one">timing</span><span className="signal-chip chip-two">choices</span><span className="signal-chip chip-three">words</span><span className="signal-chip chip-four">focus</span></div><div className="signals-copy"><span className="eyebrow">A fuller picture</span><h2>Built around the way children interact.</h2><p>Every response tells a small part of the story. Dyscover can organize accuracy, reaction time, hesitation, and interaction events at the trial level. Optional gaze research stays separate and consent-based.</p><div className="signal-list"><div><strong>01</strong><span>Response</span></div><div><strong>02</strong><span>Timing</span></div><div><strong>03</strong><span>Interaction</span></div></div><Link className="text-link" to="/research">Explore the research direction <span>↗</span></Link></div></section>
  <section className="section parent-preview"><div className="section-heading"><span className="eyebrow">For grown-ups</span><h2>A calmer view of the journey.</h2><p>The parent space is designed for thoughtful conversations, not alarming scores.</p></div><div className="preview-window"><div className="preview-topbar"><span className="preview-dot" /><span className="preview-dot" /><span className="preview-dot" /><span className="preview-label">Alex's Dyscover journey <b>Demo view</b></span></div><div className="preview-body"><div className="preview-welcome"><span className="eyebrow">Good morning</span><h3>Let's see what Alex explored.</h3><p>Latest screening · just now</p></div><div className="preview-chart"><div className="chart-line"><i /><i /><i /><i /><i /><i /></div><div className="chart-labels"><span>Explore</span><span>Notice</span><span>Grow</span></div></div><div className="preview-metrics"><div><span>Observed areas</span><strong>04</strong></div><div><span>Activities</span><strong>--</strong></div><div><span>Next step</span><strong>Ready</strong></div></div></div></div><Link className="text-link preview-link" to="/parent/dashboard">Visit the parent space <span>↗</span></Link></section>
  <section className="lexi-banner"><Mascot mood="happy" size="medium" /><div><span className="eyebrow">A friendly guide</span><h2>Meet Lexi.</h2><p>A gentle companion for questions, hints, and the next little step.</p></div><button className="button button-light" onClick={() => document.querySelector<HTMLButtonElement>('.lexi-toggle')?.click()}>Say hello <span>→</span></button></section>
  <section className="section care-section"><div className="section-heading centered"><span className="eyebrow">Designed with care</span><h2>Warmth and intelligence, together.</h2></div><div className="care-grid"><div><span className="care-icon">◌</span><h3>Accessible</h3><p>Readable type, clear focus, reduced motion, and room to go at your own pace.</p></div><div><span className="care-icon">⌂</span><h3>Privacy-aware</h3><p>Only the information needed for a thoughtful screening experience belongs here.</p></div><div><span className="care-icon">✧</span><h3>Non-diagnostic</h3><p>We describe observed patterns, never a label or a clinical conclusion.</p></div></div></section>
  <section className="final-cta"><span className="eyebrow">Your next little step</span><h2>Ready to explore?</h2><p>Come see what learning can look like when curiosity leads the way.</p><Link className="button button-sun" to="/child/home">Start Dyscover <span>→</span></Link></section>
</>; }

function About() { return <><section className="split-hero about-hero"><div><span className="eyebrow">About Dyscover</span><h1>Different doesn't mean less.</h1><p className="hero-lede">Dyslexia is a language-based learning difference. With the right support, children can find confident, creative ways to learn.</p></div><div className="about-illustration"><div className="letter-tile tile-a">a</div><div className="letter-tile tile-b">b</div><div className="letter-tile tile-c">?</div><div className="about-sun">✦</div><Mascot mood="happy" size="medium" /></div></section><section className="section narrative-section"><SectionHeader eyebrow="A little more context" title="Some words take a different path." /><div className="topic-grid">{[['Reading', 'Finding a rhythm in words can take extra time.'], ['Writing', 'Ideas can be clear even when putting them on paper feels hard.'], ['Spelling', 'Sounding out and remembering word patterns may need support.'], ['Sound patterns', 'Listening for small differences in language is a skill that grows.']].map(([title, text], index) => <Card key={title} className={`topic-card topic-${index}`}><span className="topic-index">0{index + 1}</span><h3>{title}</h3><p>{text}</p></Card>)}</div></section><section className="section promise-section"><div className="promise-card"><MascotBubble mood="thinking">Dyscover is here to help adults ask better questions.</MascotBubble><div><span className="eyebrow">What Dyscover does</span><h2>It creates space to notice.</h2><p>Interactive activities can help families and educators organize observations about language, symbols, timing, and interaction.</p></div></div><div className="not-card"><span className="eyebrow">What Dyscover does not do</span><h2>It never gives a diagnosis.</h2><p>This is a screening and support experience, not a clinical evaluation. Observed indicators are one part of a much bigger picture.</p><Link className="text-link" to="/research">Read our limitations <span>↗</span></Link></div></section><section className="support-band"><div><span className="eyebrow">Why early support matters</span><h2>When adults understand more, children carry less.</h2></div><p>Early, kind support can make learning feel less lonely and give strengths more room to show up.</p></section></>; }

function HowItWorks() { const steps = [['01', 'Create a profile', 'A private display name is enough to begin.'], ['02', 'Play', 'Short activities invite curiosity, not pressure.'], ['03', 'Observe', 'Trials can keep response and interaction events together.'], ['04', 'Understand', 'A screening profile describes what was observed.'], ['05', 'Support', 'The next step is a conversation, not a label.']]; return <><PageHeader eyebrow="How Dyscover works" title="Follow the little path." ><p className="page-lede">From a first hello to a clearer conversation, each step has a purpose.</p></PageHeader><section className="journey"><div className="journey-line" />{steps.map(([number, title, copy], index) => <div className={`journey-step journey-step-${index + 1}`} key={number}><div className="journey-node"><span>{number}</span></div><div className="journey-copy"><span className="eyebrow">Step {number}</span><h2>{title}</h2><p>{copy}</p></div><div className="journey-art">{index === 0 && <span>⌂</span>}{index === 1 && <span>✦</span>}{index === 2 && <span>⌕</span>}{index === 3 && <span>◌</span>}{index === 4 && <span>⌁</span>}</div></div>)}</section><section className="section centered-callout"><MascotBubble mood="excited">There is no right or wrong way to be you.</MascotBubble><Link className="button button-sun" to="/child/home">Enter the explorer space <span>→</span></Link></section></>; }

function Research() { return <><PageHeader eyebrow="Research direction" title="Useful structure without overclaiming."><p className="page-lede">The world can feel playful while the architecture underneath stays careful.</p></PageHeader><section className="research-flow"><div className="research-grid-bg" /><div className="research-flow-step"><span>01</span><strong>Game interaction</strong><small>playful trials</small></div><i>↓</i><div className="research-flow-step"><span>02</span><strong>Behavioral signals</strong><small>responses and timing</small></div><i>↓</i><div className="research-flow-step"><span>03</span><strong>Feature extraction</strong><small>structured research data</small></div><i>↓</i><div className="research-flow-step"><span>04</span><strong>Screening profile</strong><small>clearer conversations</small></div></section><section className="section current-future"><Card className="current-card"><Badge>Current architecture</Badge><h2>Ready to hold thoughtful observations.</h2><p>Stage 1 defines the path from child profile to assessment session, game, trial, event, and optional research signal.</p><div className="feature-pills"><span>trial events</span><span>timing</span><span>accuracy</span><span>fixations</span></div></Card><Card className="future-card"><Badge>Research direction</Badge><h2>Ready to learn, not ready to claim.</h2><p>Future work can validate features and models with care. No clinical thresholds or hard-coded probabilities belong here.</p><div className="gaze-visual"><span className="gaze-cross">+</span><span className="gaze-ring ring-one" /><span className="gaze-ring ring-two" /></div></Card></section><section className="section research-note"><Mascot mood="thinking" size="small" /><div><span className="eyebrow">A useful boundary</span><h2>Patterns are not diagnoses.</h2><p>Any result should be interpreted alongside context and, when needed, professional evaluation.</p></div></section></>; }

function Contact() { const [sent, setSent] = useState(false); return <><section className="split-hero contact-hero"><div><span className="eyebrow">Contact</span><h1>Bring a thoughtful question.</h1><p className="hero-lede">We'd love to hear from parents, educators, researchers, and curious collaborators.</p><div className="contact-doodle"><span>✦</span><span>↗</span><span>◌</span><span>⌁</span></div><p className="contact-email">support@dyscover.org</p></div><Card className="contact-form-card">{sent ? <div className="form-success"><Mascot mood="happy" size="small" /><h2>Message received.</h2><p>Thank you for reaching out. We'll be in touch.</p><button className="text-link" onClick={() => setSent(false)}>Send another message <span>↗</span></button></div> : <form onSubmit={(event) => { event.preventDefault(); setSent(true); }}><span className="eyebrow">Say hello</span><label htmlFor="name">Your name<input id="name" name="name" required /></label><label htmlFor="email">Email address<input id="email" name="email" type="email" required /></label><label htmlFor="message">Your message<textarea id="message" name="message" rows={5} required /></label><Button type="submit">Send message <span>→</span></Button></form>}</Card></section></>; }


function ChildHome() { return <div className="child-space"><div className="child-topbar"><Link className="child-brand" to="/"><span className="brand-mark">✦</span>Dyscover</Link><Link className="child-exit" to="/">Grown-up space <span>↗</span></Link></div><section className="child-welcome"><div className="child-copy"><span className="child-kicker">✦ explorer mode ✦</span><h1>Hi, Explorer!</h1><p>Ready for today's adventure?</p><MascotBubble mood="happy">Take your time. We can explore together.</MascotBubble><Link className="child-start" to="/child/assessment">Start adventure <span>→</span></Link></div><div className="child-scene"><div className="child-moon">✦</div><div className="child-cloud cloud-one" /><div className="child-cloud cloud-two" /><div className="child-ground" /><div className="child-path" /><Mascot mood="excited" size="large" /></div></section><section className="child-journey-card"><div className="child-card-heading"><div><span className="child-kicker">your journey</span><h2>A little path, one step at a time.</h2></div><span className="journey-count">0 / 5</span></div><div className="star-progress"><span className="active">✦</span><i /><span>✦</span><i /><span>✦</span><i /><span>✦</span><i /><span>✦</span></div><div className="child-quick-links"><Link to="/child/assessment"><span>✦</span><strong>My activities</strong><small>Choose an adventure</small></Link><Link to="/child/practice"><span>⌁</span><strong>Let's practise</strong><small>A friendly practice zone</small></Link><Link to="/parent/dashboard"><span>◌</span><strong>My grown-up</strong><small>See your journey</small></Link></div></section></div>; }

function Assessment() { return <ChildAssessmentHub />; }
function VisualAssessment() { return <GameRunner />; }
function SpeechAssessment() { return <SpeechAssessmentRunner />; }

export function App() { return <Layout><Routes><Route path="/" element={<Home />} /><Route path="/about" element={<About />} /><Route path="/how-it-works" element={<HowItWorks />} /><Route path="/research" element={<Research />} /><Route path="/contact" element={<Contact />} /><Route path="/parent/dashboard" element={<ParentDashboard />} /><Route path="/child/home" element={<ChildHome />} /><Route path="/child/assessment" element={<Assessment />} /><Route path="/child/assessment/visual" element={<VisualAssessment />} /><Route path="/child/assessment/speech" element={<SpeechAssessment />} /><Route path="/child/practice" element={<PracticeRunner />} /><Route path="*" element={<Home />} /></Routes></Layout>; }
