import { api, request } from '../services/apiClient';
import { enqueue, flushQueue, type PersistedItem } from './engine';
import type { AssessmentEvent, AssessmentSession, GameResult, Trial } from './engine';

const childKey = 'dyscover-stage2-child-id';
export async function ensureAssessmentSession(): Promise<AssessmentSession> { let childId = localStorage.getItem(childKey); if (!childId) { const child = await api.createChild({ display_name: 'Explorer' }); childId = child.id; localStorage.setItem(childKey, childId); } const assessment = await api.createAssessment({ child_id: childId, version: 'stage-2.0' }); return { sessionId: assessment.id, assessmentId: assessment.id, childId, assessmentVersion: assessment.version, startedAt: new Date().toISOString(), status: 'NOT_STARTED', games: [], currentGameIndex: 0, totalTrials: 0 }; }
export async function persistTrial(assessmentId: string, gameId: string, trial: Trial): Promise<void> { const payload = { trial_number: trial.trialIndex + 1, stimulus: trial.stimulus, expected_response: trial.expectedResponse, actual_response: trial.actualResponse, game_version: trial.gameVersion, domain: trial.domain, difficulty: trial.difficulty, score: trial.score, attempt_count: trial.attemptCount, error_count: trial.errorCount, metadata: trial.metadata, correctness: trial.correct, reaction_time_ms: trial.reactionTimeMs, hesitation_time_ms: trial.hesitationTimeMs, started_at: trial.startedAt, completed_at: trial.completedAt }; const item: PersistedItem = { kind: 'trial', path: `/assessments/${assessmentId}/games/${gameId}/trials`, payload: payload as unknown as Trial }; try { await api.createTrial(assessmentId, gameId, payload); } catch { enqueue(item); } }
export async function persistEvent(trialId: string, event: AssessmentEvent): Promise<void> { const payload = { event_type: event.eventType, session_id: event.sessionId, game_id: event.gameId, timestamp: event.timestamp, performance_time: event.performanceTime, sequence_number: event.sequenceNumber, schema_version: event.schemaVersion, payload: event.payload }; const item: PersistedItem = { kind: 'event', path: `/trials/${trialId}/events`, payload: payload as unknown as AssessmentEvent }; try { await api.createEvent(trialId, payload); } catch { enqueue(item); } }
export async function persistSummary(assessmentId: string, summary: { games: GameResult[]; totalTrials: number }): Promise<void> { try { await api.createSummary(assessmentId, summary); } catch { enqueue({ kind: 'event', path: `/assessments/${assessmentId}/summary`, payload: summary as unknown as AssessmentEvent }); } }
export async function flushAssessmentQueue(): Promise<void> { await flushQueue(async item => { await request(item.path, { method: 'POST', body: JSON.stringify(item.payload) }); }); }
