import type { ReactNode } from 'react';
import { Link } from 'react-router-dom';
import { Button, Mascot } from '../../components/ui';
import type { GameState } from '../engine';

export function GameShell({ title, mission, totalMissions, state, children, instructions, onPause, feedback, onHelp }: { title: string; mission: number; totalMissions: number; state: GameState; children: ReactNode; instructions: string[]; onPause: () => void; feedback?: string; onHelp: () => void }) {
  const progress = Math.round((mission / totalMissions) * 100);
  return <div className="game-shell"><div className="game-topbar"><Link className="game-back" to="/child/assessment" aria-label="Leave activity">←</Link><div className="game-title"><span className="game-mascot-dot">✦</span><strong>{title}</strong></div><div className="game-actions"><button className="game-icon-button" onClick={onHelp} aria-label="Show instructions">?</button><button className="game-icon-button" onClick={onPause} aria-label={state === 'PAUSED' ? 'Resume activity' : 'Pause activity'}>{state === 'PAUSED' ? '▶' : 'Ⅱ'}</button></div></div><div className="game-progress-row"><span>Mission {mission + 1} of {totalMissions}</span><div className="game-progress"><span style={{ width: `${progress}%` }} /></div><span>{progress}%</span></div><main className="game-stage"><div className="game-intro"><span className="child-kicker">{state === 'PAUSED' ? 'paused for a moment' : 'take your time'}</span><h1>{instructions[0]}</h1><p>{instructions[1]}</p></div>{children}{feedback && <div className="game-feedback" role="status"><Mascot mood={feedback === 'Great job!' ? 'happy' : 'thinking'} size="small" /><strong>{feedback}</strong></div>}</main>{state === 'PAUSED' && <div className="game-pause-overlay" role="dialog" aria-modal="true" aria-label="Activity paused"><Mascot mood="thinking" size="medium" /><span className="child-kicker">a small pause</span><h2>Ready when you are.</h2><p>Your adventure is waiting right where you left it.</p><button className="child-start" onClick={onPause}>Continue <span>→</span></button></div>}</div>;
}

export function GameIntro({ title, instructions, onStart }: { title: string; instructions: string[]; onStart: () => void }) { return <div className="game-intro-card"><Mascot mood="excited" size="medium" /><span className="child-kicker">new adventure</span><h1>{title}</h1><p>{instructions.join(' ')}</p><Button onClick={onStart}>Let's go <span>→</span></Button></div>; }

export function GameComplete({ title, completed, total, onContinue }: { title: string; completed: number; total: number; onContinue: () => void }) { return <div className="game-complete"><Mascot mood="excited" size="large" /><span className="child-kicker">mission complete</span><h1>You did it!</h1><p>You explored {completed} of {total} clues in {title}.</p><Button onClick={onContinue}>Continue the adventure <span>→</span></Button></div>; }
