import type { ReactNode } from 'react';
import { Link } from 'react-router-dom';
import { Button, Mascot } from '../../components/ui';
import { useLanguage } from '../../l10n';
import type { GameState } from '../engine';

export function GameShell({ title, mission, totalMissions, state, children, instructions, onPause, feedback, onHelp }: { title: string; mission: number; totalMissions: number; state: GameState; children: ReactNode; instructions: string[]; onPause: () => void; feedback?: string; onHelp: () => void }) {
  const { t } = useLanguage();
  const progress = Math.round((mission / totalMissions) * 100);
  return <div className="game-shell"><div className="game-topbar"><Link className="game-back" to="/child/assessment" aria-label={t('game.shell.leave')}>←</Link><div className="game-title"><span className="game-mascot-dot">✦</span><strong>{title}</strong></div><div className="game-actions"><button className="game-icon-button" onClick={onHelp} aria-label={t('game.shell.instructions')}>?</button><button className="game-icon-button" onClick={onPause} aria-label={state === 'PAUSED' ? t('game.shell.resume') : t('game.shell.pause')}>{state === 'PAUSED' ? '▶' : 'Ⅱ'}</button></div></div><div className="game-progress-row"><span>{t('game.shell.missionOf', { mission: mission + 1, total: totalMissions })}</span><div className="game-progress"><span style={{ width: `${progress}%` }} /></div><span>{progress}%</span></div><main className="game-stage"><div className="game-intro"><span className="child-kicker">{state === 'PAUSED' ? t('game.shell.kickerPaused') : t('game.shell.kickerPlaying')}</span><h1>{instructions[0]}</h1><p>{instructions[1]}</p></div>{children}{feedback && <div className="game-feedback" role="status"><Mascot mood={feedback === t('game.shell.feedbackGreat') ? 'happy' : 'thinking'} size="small" /><strong>{feedback}</strong></div>}</main>{state === 'PAUSED' && <div className="game-pause-overlay" role="dialog" aria-modal="true" aria-label={t('game.shell.pauseTitle')}><Mascot mood="thinking" size="medium" /><span className="child-kicker">{t('game.shell.pauseKicker')}</span><h2>{t('game.shell.pauseTitle')}</h2><p>{t('game.shell.pauseCopy')}</p><button className="child-start" onClick={onPause}>{t('game.shell.pauseContinue')} <span>→</span></button></div>}</div>;
}

export function GameIntro({ title, instructions, onStart }: { title: string; instructions: string[]; onStart: () => void }) { const { t } = useLanguage(); return <div className="game-intro-card"><Mascot mood="excited" size="medium" /><span className="child-kicker">{t('game.intro.kicker')}</span><h1>{title}</h1><p>{instructions.join(' ')}</p><Button onClick={onStart}>{t('game.intro.start')} <span>→</span></Button></div>; }

export function GameComplete({ title, completed, total, onContinue }: { title: string; completed: number; total: number; onContinue: () => void }) { const { t } = useLanguage(); return <div className="game-complete"><Mascot mood="excited" size="large" /><span className="child-kicker">{t('game.complete.kicker')}</span><h1>{t('game.complete.title')}</h1><p>{t('game.complete.copy', { completed, total, title })}</p><Button onClick={onContinue}>{t('game.complete.continue')} <span>→</span></Button></div>; }