import type { AssessmentDomain } from '../../types/assessment';

export type GameState = 'LOADING' | 'INTRO' | 'READY' | 'PLAYING' | 'PAUSED' | 'FEEDBACK' | 'TRIAL_COMPLETE' | 'GAME_COMPLETE' | 'ERROR' | 'ABANDONED';
export type AssessmentStatus = 'NOT_STARTED' | 'IN_PROGRESS' | 'PAUSED' | 'COMPLETED' | 'ABANDONED' | 'ERROR';
export type EventType = 'SESSION_STARTED' | 'SESSION_PAUSED' | 'SESSION_RESUMED' | 'SESSION_COMPLETED' | 'SESSION_ABANDONED' | 'GAME_STARTED' | 'GAME_COMPLETED' | 'TRIAL_STARTED' | 'STIMULUS_SHOWN' | 'RESPONSE_STARTED' | 'RESPONSE_SUBMITTED' | 'SPEECH_FEATURES' | 'TRIAL_COMPLETED' | 'TRIAL_TIMEOUT' | 'BUTTON_CLICKED' | 'OPTION_SELECTED' | 'OPTION_DESELECTED' | 'DRAG_STARTED' | 'DRAG_MOVED' | 'DRAG_DROPPED' | 'HINT_SHOWN' | 'HINT_USED' | 'ERROR_OCCURRED';

export interface AssessmentSession { sessionId: string; assessmentId?: string; childId?: string; assessmentVersion: string; startedAt: string; completedAt?: string; status: AssessmentStatus; games: GameResult[]; currentGameIndex: number; totalTrials: number; eventSequence?: number; }
export interface Trial { trialId: string; sessionId: string; gameId: string; gameVersion: string; trialIndex: number; domain: AssessmentDomain; difficulty: number; startedAt: string; stimulusPresentedAt?: string; responseAt?: string; completedAt?: string; stimulus: unknown; expectedResponse: unknown; actualResponse?: unknown; correct?: boolean; score: number; reactionTimeMs?: number; hesitationTimeMs?: number; attemptCount: number; errorCount: number; metadata: Record<string, unknown>; }
export interface AssessmentEvent { eventId: string; sessionId: string; trialId?: string; gameId?: string; timestamp: string; performanceTime: number; eventType: EventType; sequenceNumber: number; payload: Record<string, unknown>; schemaVersion: string; }
export interface TrialEvaluation { correct: boolean; score: number; actualResponse: unknown; metadata?: Record<string, unknown>; }
export interface GameResult { gameId: string; domain: AssessmentDomain; gameVersion: string; trialsCompleted: number; totalTrials: number; accuracy: number; meanReactionTimeMs: number; completionRate: number; errorRate: number; difficultyProgression: number[]; hintsUsed: number; }
export interface TrialContext { session: AssessmentSession; trial: Trial; emit: (eventType: EventType, payload?: Record<string, unknown>) => AssessmentEvent; }
export interface GameDefinition<TTrial extends Trial = Trial> { id: string; name: string; description: string; domain: AssessmentDomain; gameVersion: string; ageRange: [number, number]; estimatedDurationMinutes: number; difficultyLevels: number[]; instructions: string[]; totalTrials: number; createTrial: (input: { index: number; difficulty: number; random: SeededRandom; sessionId: string }) => TTrial; evaluateResponse: (trial: TTrial, response: unknown) => TrialEvaluation; getNextDifficulty: (history: TTrial[]) => number; }
export interface GameInstance { sessionId: string; game: GameDefinition; currentTrial: number; state: Record<string, unknown>; }
export interface GameCallbacks { onTrialStart?: (trial: number) => void; onInteraction?: (event: Record<string, unknown>) => void; onResponse?: (response: string) => void; onTrialComplete?: (trial: number) => void; onGameComplete?: () => void; }
export interface SeededRandom { next: () => number; int: (min: number, max: number) => number; pick: <T>(items: T[]) => T; shuffle: <T>(items: T[]) => T[]; }
